# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-12 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='Issue',
            new_name='issue',
        ),
    ]
