# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-20 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0003_issue_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='user',
        ),
    ]
