# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 10:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='subscription_end',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 21, 10, 45, 16, 769000, tzinfo=utc)),
        ),
    ]
