# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 13:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0003_auto_20170725_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='subscription_end',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 25, 13, 22, 30, 776000, tzinfo=utc)),
        ),
    ]
