# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 10:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0004_auto_20170725_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='subscription_end',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 1, 10, 14, 37, 256000, tzinfo=utc)),
        ),
    ]
