# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_feature_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='comments',
            field=models.CharField(default='', max_length=255),
        ),
    ]
