# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='votes',
        ),
    ]
