# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0007_remove_feature_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comments',
            field=models.TextField(),
        ),
    ]
