# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0006_auto_20170629_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='bug',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
