# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0008_remove_bug_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
