# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0012_auto_20170707_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='bug',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bug_votes', to='bugs.Bug'),
        ),
    ]
